version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
    security-updates: true
