import React, { useEffect, useRef, useState } from "react";

interface Caption {
  start: number;
  end: number;
  text: string;
  highlight?: boolean;
}

const sampleCaptions: Caption[] = [
  { start: 0, end: 5, text: "Welcome to Chai VC Platform", highlight: true },
  { start: 5, end: 10, text: "This onboarding video will guide you." },
  { start: 10, end: 15, text: "Captions are generated by AI." },
];

export default function Onboarding() {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const [currentCaption, setCurrentCaption] = useState<Caption | null>(null);

  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;
    const updateCaption = () => {
      const time = video.currentTime;
      const caption = sampleCaptions.find(c => time >= c.start && time < c.end) || null;
      setCurrentCaption(caption);
    };
    video.addEventListener("timeupdate", updateCaption);
    return () => video.removeEventListener("timeupdate", updateCaption);
  }, []);

  return (
    <div style={{ maxWidth: 640, margin: "0 auto" }}>
      <h1>Onboarding Video</h1>
      <video ref={videoRef} controls style={{ width: "100%" }}>
        <source src="/onboarding.mp4" type="video/mp4" />
        Your browser does not support the video tag.
      </video>
      {currentCaption && (
        <div
          style={{
            background: currentCaption.highlight ? "yellow" : "rgba(0,0,0,0.7)",
            color: currentCaption.highlight ? "black" : "white",
            padding: "8px",
            marginTop: "4px",
          }}
        >
          {currentCaption.text}
        </div>
      )}
    </div>
  );
}
