// onboarding_controller.ts - provides AI-generated captions and highlights
// for onboarding videos. This is a stub demonstrating expected behavior.

export interface Caption {
  start: number;
  end: number;
  text: string;
  highlight?: boolean;
}

export class OnboardingController {
  /**
   * generateCaptions would normally call an AI service to generate captions
   * and highlight key phrases. Here we return static sample data.
   */
  generateCaptions(): Caption[] {
    return [
      { start: 0, end: 5, text: "Welcome to Chai VC Platform", highlight: true },
      { start: 5, end: 10, text: "This onboarding video will guide you." },
      { start: 10, end: 15, text: "Captions are generated by AI." },
    ];
  }
}
