[package]
name = "pallet-did"
version = "0.1.0"
edition = "2021"

[dependencies]
frame-support = { version = "8.0.0", default-features = false }
frame-system  = { version = "8.0.0", default-features = false }
sp-runtime    = { version = "10.0.0", default-features = false }
sp-std        = { version = "6.0.0", default-features = false }
scale-info    = { version = "2", default-features = false, features = ["derive"] }
parity-scale-codec = { version = "3", default-features = false, features = ["derive"] }

[dev-dependencies]
frame-support = { version = "8.0.0" }
frame-system  = { version = "8.0.0" }
sp-runtime    = { version = "10.0.0" }
sp-std        = { version = "6.0.0" }

[features]
default = ["std"]
std = [
  "frame-support/std",
  "frame-system/std",
  "sp-runtime/std",
  "sp-std/std",
  "scale-info/std",
  "parity-scale-codec/std",
]
try-runtime = []
