name: CI

on:
  push:
    branches: ["main", "work"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install flake8
      - run: flake8 ai-matcher-service

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install pytest
      - run: pytest ai-matcher-service/tests

  docker-build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3
      - name: Build ai-matcher-service image
        run: docker build -t ai-matcher-service ./ai-matcher-service
      - name: Build backend image
        run: docker build -t backend ./backend
