name: e2e-nightly
on:
  schedule:
    - cron: "30 9 * * *" # 1:30am PT
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9.7.0 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: pnpm
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm build
      - run: pnpm e2e
