name: Prompt A/B Testing

on:
  pull_request:
    paths:
      - 'prompts/**'
      - 'scripts/**'
      - '.github/workflows/prompt_ab_test.yml'

jobs:
  ab-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run A/B tests
        run: python scripts/prompt_ab_test.py
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: ab-test-results
          path: reports/ab_test_results.json
